HumberStudentGroup/Controllers/GroupsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HumberStudentGroup.ADO;

namespace HumberStudentGroup.Controllers
{
    public class GroupsController : Controller

    {
        // Declaring the db to be used across the controller
        private HumberDBEntities db = new HumberDBEntities();

        public ActionResult Index(string searchTerm)
        {
            // get all the groups
            var Groups = from g in db.Groups select g;
            // if there is a search term change groups to search
            if (searchTerm != null)
            {
                Groups = Groups.Where(g => g.Title.Contains(searchTerm) || g.Desc.Contains(searchTerm));
            }
            // return view of groups
            return View(Groups.ToList().OrderByDescending(g => g.Users.Count));
        }

        public ActionResult Details(int id)
        {
            // find the group with the id
            Group group = db.Groups.Find(id);
            if (group == null)
            {
                return HttpNotFound();
            }

            // get the author
            var author = db.Users.Find(group.AuthorId);
            // set the session vars
            Session["GroupId"] = group.Id;
            Session["Author"] = author.Username;
            return View(group);
        }

        public ActionResult Create()
        {
            // create a session with the user id
            ViewBag.AuthorId = Session["UserId"];
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,Desc,AuthorId")] Group group)
        {
            // check if the model is valid
            if (ModelState.IsValid)
            {
                // find the user and create the group
                var sessionUser = db.Users.Single(m => m.Id == group.AuthorId);
                group.Users.Add(sessionUser);
                group.Chat = new Chat();
                db.Groups.Add(group);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(group);
        }

        public ActionResult Join(int id)
        {
            // find the group to join
            Group group = db.Groups.Find(id);
            // find the user that wants to join
            int userId = int.Parse(Session["UserId"].ToString());
            User sessionUser = db.Users.Single(m => m.Id == userId);
            if (group == null)
            {
                return HttpNotFound();
            }
            // add the user to the group
            group.Users.Add(sessionUser);
            db.SaveChanges();
            return RedirectToAction("Details", group);
        }

        public ActionResult Leave(int id)
        {
            // find the group
            Group group = db.Groups.Find(id);
            int userId = int.Parse(Session["UserId"].ToString());
            User sessionUser = db.Users.Single(m => m.Id == userId);
            if (group == null || userId == group.AuthorId)
            {
                return HttpNotFound();
            }
            // remove the user from the group
            group.Users.Remove(sessionUser);
            db.SaveChanges();
            return RedirectToAction("Details", group);
        }

        public ActionResult Edit(int id)
        {
            // find the group to edit
            ViewBag.AuthorId = Session["UserId"];
            Group group = db.Groups.Find(id);
            if (group == null)
            {
                return HttpNotFound();
            }
            return View(group);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,Desc,AuthorId")] Group group)
        {
            // if the model is valid apply the updates
            if (ModelState.IsValid)
            {
                db.Entry(group).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(group);
        }

        public ActionResult Delete(int? id)
        {
            // check if the id is null
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            // find the group
            Group group = db.Groups.Find(id);
            if (group == null)
            {
                return HttpNotFound();
            }
            // return the group
            return View(group);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            // check if the user wants to delete this group and save
            Group group = db.Groups.Find(id);
            group.Users.Clear();
            db.Groups.Remove(group);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HumberStudentGroup/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HumberStudentGroup.ADO;

namespace HumberStudentGroup.Controllers
{
    public class PostsController : Controller
    {
        private HumberDBEntities db = new HumberDBEntities();

        public ActionResult Index()
        {
            // get the db posts to index
            return View(db.Posts.ToList());
        }

        public ActionResult Details(int? id)
        {
            // chck if the id is null
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            // find the posts from the database
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            //return the post
            return View(post);
        }


        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(int? groupId, [Bind(Include = "Id,Title,Body")] Post post)
        {
            // find the user from the session
            int userId = int.Parse(Session["UserId"].ToString());
            if (ModelState.IsValid)
            {
                // create the posts and save
                post.User = db.Users.Single(m => m.Id == userId);
                post.Groups.Add(db.Groups.Single(g => g.Id == groupId));
                db.Posts.Add(post);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(post);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            // find the post from the id
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,Body")] Post post)
        {
            // if the model is valid proform edits
            if (ModelState.IsValid)
            {
                db.Entry(post).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(post);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            // find the post for deleting
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            // if the post is confiremd to delete
            Post post = db.Posts.Find(id);
            db.Posts.Remove(post);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HumberStudentGroup/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HumberStudentGroup.ADO;
using HumberStudentGroup.Models;

namespace HumberStudentGroup.Controllers
{
    public class SearchController : Controller
    {
        // GET: Search
        private HumberDBEntities db = new HumberDBEntities();

        public ActionResult Index(string searchTerm)
        {
            // get all items from these tables
            var Groups = from g in db.Groups select g;
            var Posts = from p in db.Posts select p;
            var Users = from u in db.Users select u;

            // check if there is a search term
            if (searchTerm != null)
            {
                Groups = Groups.Where(g => g.Title.Contains(searchTerm) || g.Desc.Contains(searchTerm));
                Posts = Posts.Where(p => p.Title.Contains(searchTerm) || p.Body.Contains(searchTerm));
                Users = Users.Where(u => u.Username.Contains(searchTerm));
            }
            // set the order of the models
            var GroupList = Groups.ToList().OrderByDescending(g => g.Users.Count);
            var PostList = Posts.ToList().OrderByDescending(g => g.Title);
            var UserList = Users.ToList().OrderByDescending(g => g.Username);

            // Create a searchModel and add the models to return
            SearchModelView models = new SearchModelView();
            models.Groups = GroupList;
            models.Posts = PostList;
            models.Users = UserList;

            return View(models);
        }
    }
}

HumberStudentGroup/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HumberStudentGroup.ADO;

namespace HumberStudentGroup.Controllers
{
    public class UsersController : Controller
    {
        private HumberDBEntities db = new HumberDBEntities();

        public ActionResult Signout() 
        {
            // if the user wants to sign out clear the session
            Session.Clear();
            return RedirectToAction("Index");
        }

        public ActionResult Index()
        {
            // get the users from the database
            return View(db.Users.ToList());
        }

        public ActionResult Details(int? id)
        {
            // check if the id is null
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            // find the user from the id
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            // return the user view
            return View(user);
        }

        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Username,Password")] User user)
        {
            // if the model is valid add it to the db
            if (ModelState.IsValid)
            {
                user.Type = "Student";
                db.Users.Add(user);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(user);
        }

        public ActionResult Edit(int? id)
        {
            // check if the id is null
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            // find the user through its id
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }

            // return the user view
            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Username,Password")] User user)
        {
            // check if the user model is valid
            if (ModelState.IsValid)
            {
                // apply chanes and save
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(user);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            // find the uesr throught its id
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            // return the user view
            return View(user);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            // find the user that is going to be deleted
            User user = db.Users.Find(id);
            db.Users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HumberStudentGroup/Views/Search/Index.cshtml
@model HumberStudentGroup.Models.SearchModelView
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutGroup.cshtml";
}

<style>
    .layout {
        padding: 50px;
    }
</style>

<div class="layout">
    <h2 style="text-align: center;padding-bottom: 25px">Search Page</h2>

    <form asp-action="Index" method="get">
        <p class="searchBar" style="text-align: center">
            <input style="padding-left: 5px;border-radius:2rem;border: 3px solid #123456; width: 300px;" class="searchField" type="text" name="SearchTerm" placeholder="Enter a Key word" />
            <input type="submit" value="Search" class="btn btn-primary" />
            <input type="submit" value="Clear" class="btn btn-danger" />
        </p>
    </form>

    <h1>
        Search List
    </h1>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Type</th>
                <th scope="col">ID</th>
                <th scope="col">Title</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Groups)
            {
                <tr>
                    <th scope="row">Group</th>
                    <th scope="row">@item.Id</th>
                    <td>@Html.DisplayFor(modelItem => item.Title)</td>
                    <td>
                        <input type="button" class="btn btn-info" value="View Group" onclick="location.href='@Url.Action("Details", "Groups", new { id = item.Id })'" />
                        <input type="button" class="btn btn-warning" value="Edit Group" onclick="location.href='@Url.Action("Edit", "Groups", new { id = item.Id })'" />
                        <input type="button" class="btn btn-danger" value="Delete Group" onclick="location.href='@Url.Action("Delete", "Groups", new { id = item.Id })'" />
                    </td>
                </tr>
            }
            @foreach (var item in Model.Posts)
            {
                <tr>
                    <th scope="row">Post</th>
                    <th scope="row">@item.Id</th>
                    <td>@Html.DisplayFor(modelItem => item.Title)</td>
                    <td>
                        <input type="button" class="btn btn-info" value="View Post" onclick="location.href='@Url.Action("Details", "Posts", new { id = item.Id })'" />
                        <input type="button" class="btn btn-warning" value="Edit Post" onclick="location.href='@Url.Action("Edit", "Posts", new { id = item.Id })'" />
                        <input type="button" class="btn btn-danger" value="Delete Post" onclick="location.href='@Url.Action("Delete", "Posts", new { id = item.Id })'" />
                    </td>
                </tr>
            }
            @foreach (var item in Model.Users)
            {
                <tr>
                    <th scope="row">User</th>
                    <th scope="row">@item.Id</th>
                    <td>@Html.DisplayFor(modelItem => item.Username)</td>
                    <td>
                        <input type="button" class="btn btn-info" value="View User" onclick="location.href='@Url.Action("Details", "Users", new { id = item.Id })'" />
                        <input type="button" class="btn btn-warning" value="Edit User" onclick="location.href='@Url.Action("Edit", "Users", new { id = item.Id })'" />
                        <input type="button" class="btn btn-danger" value="Delete User" onclick="location.href='@Url.Action("Delete", "Users", new { id = item.Id })'" />
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>