HumberStudentGroup/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HumberStudentGroup.ADO;

namespace HumberStudentGroup.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            using (HumberDBEntities context = new HumberDBEntities())
            {
                // get the groups as index
                return View(context.Groups.ToList());
            }
        }
        public ActionResult About()
        {
            return View();
        }
    }
}

HumberStudentGroup/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HumberStudentGroup.ADO;

namespace HumberStudentGroup.Controllers
{
    public class LoginController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AutherizeLogin(HumberStudentGroup.ADO.User user)
        {
            using (HumberDBEntities context = new HumberDBEntities())
            {
                // check if the user is in the system
                var UserLogin = context.Users.Any(m => m.Username == user.Username && m.Password == user.Password);
                if (!UserLogin)
                {
                    return View("Index", user);
                }
                else
                {
                    // create session variables to be used across the session
                    var sessionUser = context.Users.Single(m => m.Username == user.Username);
                    HttpContext.Session.Add("UserId", sessionUser.Id);
                    HttpContext.Session.Add("Username", sessionUser.Username);
                    if (sessionUser.Type.Equals("Admin"))
                    {
                        HttpContext.Session.Add("AdminView", sessionUser.Id);
                    }
                    return RedirectToAction("Index", "Home");
                }
            }
        }
    }
}

HumberStudentGroup/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HumberStudentGroup.ADO;

namespace HumberStudentGroup.Controllers
{
    public class UsersController : Controller
    {
        private HumberDBEntities db = new HumberDBEntities();

        public ActionResult Signout() 
        {
            // if the user wants to sign out clear the session
            Session.Clear();
            return RedirectToAction("Index");
        }

        public ActionResult Index()
        {
            // get the users from the database
            return View(db.Users.ToList());
        }

        public ActionResult Details(int? id)
        {
            // check if the id is null
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            // find the user from the id
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            // return the user view
            return View(user);
        }

        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Username,Password")] User user)
        {
            // if the model is valid add it to the db
            if (ModelState.IsValid)
            {
                user.Type = "Student";
                db.Users.Add(user);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(user);
        }

        public ActionResult Edit(int? id)
        {
            // check if the id is null
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            // find the user through its id
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }

            // return the user view
            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Username,Password")] User user)
        {
            // check if the user model is valid
            if (ModelState.IsValid)
            {
                // apply chanes and save
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(user);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            // find the uesr throught its id
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            // return the user view
            return View(user);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            // find the user that is going to be deleted
            User user = db.Users.Find(id);
            db.Users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HumberStudentGroup/Views/Home/About.cshtml
@model IEnumerable<HumberStudentGroup.ADO.Group>

    @{
    Layout = "~/Views/Shared/_LayoutGroup.cshtml";
    if (Session["Username"] == null)
    {
    ViewBag.UserLoggedinMessage = "Currently Not Signed In";
    } else
    {
    ViewBag.UserLoggedinMessage = "Currently Signed In as " + Session["Username"];
    }
    }

    <style>
        .HumberIMG {
            border-radius: 5px;
            border: 10px solid #CC9900;
            width: 100%;
            height: 500px;
        }

        .ImgSection {
            float: right;
            padding: 25px;
        }
    </style>


    <!DOCTYPE html>
    <html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>About HumberGroups</title>
    </head>
    <body>
        <div>
            <small style="float: right; position: relative;padding: 5px;">@ViewBag.UserLoggedinMessage</small><br />
        </div>
        <h1 style="text-align: center;">About to HumberGroups</h1>
        <div style="text-align: center; padding-top: 25px">
            <p>
                Lorem ipsum dolor sit amet. Est voluptatem aliquid eos mollitia itaque quo architecto delectus.<br>
                Et omnis aperiam a dolore aspernatur ut earum provident quo autem necessitatibus aut Quis magni.<br>
                Ut officiis molestiae quo autem voluptas ea numquam dignissimos ipsum ipsum eos accusantium magni<br>
                et adipisci quam ut nostrum ipsum. Et possimus omnis in quis repudiandae et suscipit expedita et<br>
                sint voluptas non libero beatae 33 earum eligendi At optio similique.
            </p>
        </div>
        <div style="float: left; width: 40%;">
            <div style="padding-top: 50px;">
                <p>
                    Et vitae voluptatibus ut nobis nostrum ut enim quos. Ea autem obcaecati aut omnis internos qui consequatur sint est fugit quis.
                </p>
            </div>
            <div style="padding-top: 50px;">
                <p>
                    Lorem ipsum dolor sit amet. Est voluptatem aliquid eos mollitia itaque quo architecto delectus.<br>
                    Et omnis aperiam a dolore aspernatur ut earum provident quo autem necessitatibus aut Quis magni.<br>
                    Ut officiis molestiae quo autem voluptas ea numquam dignissimos ipsum ipsum eos accusantium magni<br>
                    et adipisci quam ut nostrum ipsum. Et possimus omnis in quis repudiandae et suscipit expedita et<br>
                    sint voluptas non libero beatae 33 earum eligendi At optio similique.
                </p>
            </div>
        </div>
        <div class="ImgSection">
            <img src="https://www.montgomerysisam.com/wp-content/uploads/2018/12/1497-003.jpg" class="HumberIMG" />
        </div>
    </body>
</html>

HumberStudentGroup/Views/Home/Index.cshtml
@model IEnumerable<HumberStudentGroup.ADO.Group>

@{
    Layout = "~/Views/Shared/_LayoutGroup.cshtml";
}

<style>
    .leftSide-buttonDiv {
        padding-top: 25px;
        display: flex;
        justify-content: center;
        align-items: center;
    }

    .rightSide-buttonDiv {
        padding-bottom: 25px;
        display: flex;
        justify-content: center;
        align-items: center;
    }

    .btn {
        border-radius: 15px;
    }

    .btn-signin {
        margin: auto;
        width: 60%;
    }

    .btn-create {
        margin: auto;
        width: 80%;
    }

    .HumberIMG {
        border-radius: 5px;
        border: 10px solid #CC9900;
        width: 100%;
        height: 450px;
    }

    .ImgSection {
        padding: 25px;
    }
</style>


<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Homepage</title>
</head>
<body>
    <small style="float: right; position: relative;padding: 5px;">@ViewBag.UserLoggedinMessage</small>
    <h1>Welcome to HumberGroups</h1>
    <div style=" padding-top: 25px;">
        <div style="float: left; width: 30%;">
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
                magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
                pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim
                id est laborum.
            </p>
            <div class="leftSide-buttonDiv">
                @Html.ActionLink("Create Account", "Create", "Users", null, new { @class = "btn btn-primary btn-large btn-create" })
            </div>
        </div>
        <div style="float: right; width: 40%;">
            <div class="rightSide-buttonDiv">
                @if (Session["UserId"] == null)
                {
                    @Html.ActionLink("Sign in", "Index", "Login", null, new { @class = "btn btn-success btn-large btn-signin" })
                }
                else
                {
                    @Html.ActionLink("Sign Out", "Signout", "Users", null, new { @class = "btn btn-danger btn-large btn-signin" })
                }
            </div>
            <p>
                Lorem ipsum dolor sit amet, ipsum praesent est et, id sed libris latine delicatissimi, per stet illum praesent ad.
                Ut vix error inermis. Quo noster insolens deseruisse eu, doctus maluisset referrentur ex est, at nam munere dissentiunt.
                Ius cu invidunt lobortis indoctum, usu id omnis illum docendi, nobis consul ei pri. Te etiam discere ius, ne vero
                intellegam per, justo verterem necessitatibus usu ad. Ne mel ullum errem forensibus.Ius ut mollis deterruisset,
                consul admodum eleifend est ad, pri ne possit referrentur. Errem clita mea at, eum exerci pertinacia id, ut vis debet eligendi deleniti.
            </p>
            <p>
                Eu mei hinc dolores intellegat, ea elitr eruditi evertitur vel. Sit novum everti rationibus id, nisl malis fugit usu ex, sit affert eruditi
                scribentur in. Cu soleat postea graeco usu, indoctum intellegat ex eum. Expetendis suscipiantur ad mea.
            </p>
        </div>
    </div>
    <div class="ImgSection">
        <img src="https://humber.ca/brand/sites/default/files/styles/photo_of_campus/public/images/campus/32911.jpg?itok=RnsbpXyu" class="HumberIMG"/>
    </div>
</body>
</html>