HumberStudentGroup/Controllers/ChatController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HumberStudentGroup.ADO;

namespace HumberStudentGroup.Controllers
{
    public class ChatController : Controller
    {
        // GET: Chat
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult CreateMessage(string ChatMessage)
        {
            using (HumberDBEntities context = new HumberDBEntities())
            {
                // FIND THE GROUP/CHAT
                int GroupId = int.Parse(Session["GroupId"].ToString());

                var group = context.Groups.Single(g => g.Id == GroupId);
                // Create the Message Timestamp
                string Date = DateTime.Now.ToString("MM/dd HH:mm");

                // Creatiing the Message Obj
                var message = new Message
                {
                    Text = ChatMessage,
                    SentDate = Date,
                    UserId = Int32.Parse(Session["UserId"].ToString()),
                    ChatId = GroupId,
                };

                // Applying the Message to the chat and saving
                group.Chat.Messages.Add(message);
                context.SaveChanges();

                return RedirectToAction("Details", "Groups", group);
            }
        }

    }
}

HumberStudentGroup/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HumberStudentGroup.ADO;

namespace HumberStudentGroup.Controllers
{
    public class UsersController : Controller
    {
        private HumberDBEntities db = new HumberDBEntities();

        public ActionResult Signout() 
        {
            // if the user wants to sign out clear the session
            Session.Clear();
            return RedirectToAction("Index");
        }

        public ActionResult Index()
        {
            // get the users from the database
            return View(db.Users.ToList());
        }

        public ActionResult Details(int? id)
        {
            // check if the id is null
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            // find the user from the id
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            // return the user view
            return View(user);
        }

        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Username,Password")] User user)
        {
            // if the model is valid add it to the db
            if (ModelState.IsValid)
            {
                user.Type = "Student";
                db.Users.Add(user);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(user);
        }

        public ActionResult Edit(int? id)
        {
            // check if the id is null
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            // find the user through its id
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }

            // return the user view
            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Username,Password")] User user)
        {
            // check if the user model is valid
            if (ModelState.IsValid)
            {
                // apply chanes and save
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(user);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            // find the uesr throught its id
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            // return the user view
            return View(user);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            // find the user that is going to be deleted
            User user = db.Users.Find(id);
            db.Users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HumberStudentGroup/Views/Shared/_Chat.cshtml
@model HumberStudentGroup.ADO.Chat

@{
    ViewBag.Title = "_Chat";
    Layout = "~/Views/Shared/_LayoutGroup.cshtml";
}

<style>
    .chatbox-container {
        width: 350px;
    }

    .chatbox {
        border: 3px solid black;    
        height: 50vh;
        overflow-y: scroll;
    }

    .checkbox-container {
        vertical-align: middle;
    }

    .checkbox input {
        width: 100%;
    }

    td {
        width: 100%;
    }

    .MessageControls {
        padding-top: 5px;
        text-align: center;
        border: 3px solid black;
        background-color: lightgray;
        padding-left: 5px;
    }

    .messageSend .searchField {
        padding-left: 5px;
    }

    .btn-message {
        border-radius: 25px;
    }
</style>

<div class="chatbox-container">
    <div class="chatbox" style="">
        <table style="width: 100%;">
            <tbody>
                @foreach (var message in Model.Messages.Select((value, i) => new { i, value }))
                {
                    if (message.i % 2 == 0)
                    {
                        <tr style="width: 100%" class="chatbox-message ">
                            <td class="chatbox-message ">
                            &nbsp;@message.value.User.Username&nbsp;[@message.value.SentDate]: @message.value.Text
                            </td>
                        </tr>
                    }
                    else
                    {
                        <tr style="background-color: lightgray">
                            <td class="chatbox-message ">
                            &nbsp;@message.value.User.Username&nbsp;[@message.value.SentDate]: @message.value.Text
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
    <div class="MessageControls">
        @using (Html.BeginForm("CreateMessage", "Chat", FormMethod.Get))
        {
            <p class="messageSend">
                <b>Send: </b><input class="messageField" type="text" id="ChatMessage" name="ChatMessage" placeholder="..." />
                <input type="submit" value="Send" class="btn btn-primary btn-message" />
            </p>
        }
    </div>
</div>

HumberStudentGroup/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        body {
            color: #000033;
            background-color: white;
            font-family: Open Sans ExtraBold;
        }
    </style>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container" style="padding-bottom: 0;">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("HumberGroups", "Index", "Home", new { area = "" }, new { @class = "navbar-brand", @style= "color: #CC9900;" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav" style="color: white;">
                    <li>@Html.ActionLink("See Groups", "Index", "Groups")</li>
                    <li>@Html.ActionLink("Search", "Index", "Search")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("See Members", "Index", "Users")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <footer>
            <p></p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

HumberStudentGroup/Views/Shared/_LayoutCrud.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="layout">
        @Html.Partial("_Nav")
        @RenderBody()
        <footer>
            <p></p>
        </footer>
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
        <style>
            body {
                background-color: #009BE0;
            }

            .layout {
                margin: auto;
                width: 50%;
            }

            .control-label {
                text-decoration: underline;
            }

            .form-control {
                border-radius: 3rem;
                background-color: #CC9900;
                border: 5px solid #312c2c;
                font-size: 25px;
                min-height: 50px;
            }
        </style>
    </div>
</body>
</html>

HumberStudentGroup/Views/Shared/_LayoutGroup.cshtml
<!DOCTYPE html>

<style>
    body {
        padding: 100px;
    }
</style>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        body {
            color: #000033;
            background-color: white;
            font-family: Open Sans ExtraBold;
        }
        .form-control text-box single-line {
            border-radius: 2rem;
        }
    </style>
</head>
<body>
    @Html.Partial("_Nav")
        @RenderBody()
        <footer>
            <p></p>
        </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

HumberStudentGroup/Views/Shared/_Nav.cshtml
@{  
    if (Session["AdminView"] != null)
    {
        ViewBag.AdminMessage = "Admin access";
    }
    if (Session["Username"] != null)
    {
        //ViewBag.UserLoggedinMessage = "Currently Signed In as " + Session["Username"];
    }
}

<style>
    body {
        color: #000033;
        background-color: white;
        font-family: Open Sans ExtraBold;
    }

    .navbar-brand {
        font-size: 3rem;
    }

        .navbar-brand:hover {
            text-decoration: underline;
        }

    .navbar-inverse .navbar-nav > li > a {
        text-decoration: none;
        font-size: 2em;
        color: #0097A9;
    }

        .navbar-inverse .navbar-nav > li > a:hover {
            text-decoration: underline;
            color: #009BE0;
        }

    .navbar {
        background-color: #000033;
        padding-bottom: 0;
    }
</style>

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <a href="#" class="pull-left"><img width="32" src="https://play-lh.googleusercontent.com/If5h6y3M0SkncS1K2UBm6nqGIO0gCxBg6qhudY1k42-EzSSVWUNCigDFWLXiyzDI0oAk"></a>
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("HumberGroups", "Index", "Home", new { area = "" }, new { @class = "navbar-brand", @style = "color: #CC9900;" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav" style="color: white;">
                <li>@Html.ActionLink("See Groups", "Index", "Groups")</li>
                <li>@Html.ActionLink("Search", "Index", "Search")</li>
                <li>@Html.ActionLink("About", "About", "Home")</li>
                <li>@Html.ActionLink("See Members", "Index", "Users")</li>
            </ul>
        </div>
    </div>
</div>
<div>
    <p style="float: right; color:red; position: relative;padding: 5px;">@ViewBag.AdminMessage</p>
    <p style="float: right; color:black; position: relative;padding: 5px;">@ViewBag.UserLoggedinMessage</p>
</div>